// src/components/Toggle.tsx
import { JSXElement } from 'solid-js'
import { Show, showSignal } from './showSignal'
import './Toggle.css'

export default function Toggle(props: {
  show: Show
  children: any
}): JSXElement {
  const [show, setShow] = showSignal

  return (
    <>
      {props.show === show() ? (
        <>
          <button
            onClick={() => {
              setShow(show() === 'cards' ? 'readme' : 'cards')
            }}
          >
            {show() ? 'Show GitHub README' : 'Show link cards'}
          </button>
          {props.children}
        </>
      ) : null}
    </>
  )
}

// src/components/Toggle.svelte
<script>
  import { toggle } from '../stores/svelteStores'
  import './Toggle.css'

  export let show = 'cards'
</script>

{#if show === $toggle}
  <button
    on:click={() => {
      toggle.set($toggle === 'readme' ? 'cards' : 'readme')
    }}
  >
    {$toggle === 'cards' ? 'Show GitHub README' : 'Show link cards'}
  </button>
  <slot />
{/if}
